# Generated by Django 3.0 on 2019-12-17 00:12

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencia',
            name='pais',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
